name: busecke_etal_2021_aguadv
channels:
  - conda-forge
dependencies:
  - python=3.9
#   - cmip6_preprocessing # Need to release a new version to have the latest changes
  - cartopy
  - astropy
  - xarray
  - numpy
  - scipy
  - netcdf4
  - pandas
  - matplotlib
  - cmocean
  - regionmask
  - xesmf
  - zarr
  - h5netcdf
  - cf_xarray
  - nc-time-axis
  - xgcm
  - pip
  - xarrayutils
  # these are just upstream requirements. Make sure these are not required in the final submission
  - rechunker
  - fastprogress
  - xhistogram
  - dask
  - distributed
  - pip:
      - git+https://github.com/jbusecke/cmip6_preprocessing.git
      - git+https://github.com/jbusecke/cmip6_omz.git #TODO: Release versions for pub
