name: busecke_etal_2021_aguadv
channels:
  - conda-forge
dependencies:
  - python
  - ipykernel
  - astropy
  - dask
  - distributed
  - cartopy
  - xarray
  - numpy
  - scipy
  - dask
  - netcdf4
  - pandas
  - matplotlib
  - cmocean
  - regionmask
  - xesmf
  - zarr
  - h5netcdf
  - cf_xarray
  - nc-time-axis
  - xgcm
  - pip
  - pip:
      - git+https://github.com/jbusecke/cmip6_preprocessing.git
      - git+https://github.com/jbusecke/xarrayutils.git
      - git+https://github.com/jbusecke/cmip6_omz.git #TODO: Fix version for pub
